### ISSUE TITLE
Extension suggestions: regularization for NMF and consensus clustering

### ISSUE THREAD

**Issue by dhb2128** [dylkot/cNMF#12]
Hi Dylan,

Thanks for sharing this useful software!

I had a few quick questions:
1. Have you ever experimented with the `regularization="components"` option in the call to `non_negative_factorization` to enforce more sparsity in the gene loadings? If so, do you have any suggestions for `alpha` or `l1_ratio`?

2. Have you ever considered trying multiple values of `k` in the `consensus` clustering? For example, even if you have a 20-factor model, if you only get some factors on some fraction of restarts, you could imagine that the clustering of the `l2_spectra` might actually be better with some value of `k` that is slightly smaller or higher than `k` (e.g. you could only have 19 stable factors that you would want to keep or alternatively maybe there are actually 21 factors that reliably show up). If I look at something like the `silhouette_score` I sometimes get maximum values with values that are slightly higher than `k` but I haven't tried to use those alternative clusterings of the `l2_spectra` for any downstream applications.

3. Is there a reason why the loadings are rescaled by their norms in https://github.com/dylkot/cNMF/blob/5418be44811c59ff5e6853341b25803a67886bcb/cnmf.py#L509 but then are scaled by their sums in `median_spectra`? https://github.com/dylkot/cNMF/blob/5418be44811c59ff5e6853341b25803a67886bcb/cnmf.py#L542

**Comment by dylkot** [comment]
Hi, sorry for the slow reply! 

1. I experimented a bit with the regularization for NMF. It was a bit tricky because it shifted density between the usages and the GEP components in a non-intuitive way. Also there wasn't a very simple way to perform cross-validation to optimize those parameters. I played around a bit with matrix completion (I.e. blocking out a part of the input matrix and predicting it with NMF and using that to attempt to pick the regularization parameters). But it ultimately ended up requiring a slower solver algorithm (multiplicative update) and I dropped it but I think it is worth pursuing if you are interested. 

2. Yes, we played with the multiple values of K option a bit. At the end of the day, it didn't seem to give much better results than settling on a single K and seemed a bit needlessly complicated but I can't think of any specific contraindication to it.

3. Hi, good question. Essentially we found we were getting better consensus clusters when the components were L2 normalized -- we didn't want the overall magnitude of expression in a component to influence the clustering, just the direction. However, for interpretability of programs, it is nice for them sum to 1 so you can think of them as a probability of a count being drawn for a gene from a given program. Hence for the final programs we return, they are L1 normalized instead of L2. In practice, L1 norming in both cases did not really change the results much.

I hope that helps! Feel free to reach out by email with additional questions.
