### ISSUE TITLE
Frobenius error 

### ISSUE THREAD

**Issue by Pazuzzilla** [dylkot/cNMF#32]
Hi, 
I've runned cNMF on my dataset with 200 iteration, in selecting K i decided to start from k = 10 (the analysis was runned between 2<k<20).
K= 10 have in my case the greater stability 0.875 (i know that could not be the best but i take that as a good start point). For what concerne the error it has high value 8.15 with respect to your work (see the plot). 
<img width="1597" alt="cNMF values" src="https://user-images.githubusercontent.com/43204148/162223444-8d52147f-f49a-4268-a09c-737c03f3b773.png">
I'm not understanding very well the nature of the error computation and how to read the error values, they decrease but looking at my values they are too high? I read the referenced paper but i still have some difficulties. could you help me with the interpretation?
Thanks

**Comment by dylkot** [comment]
Hi @Pazuzzilla - I don't think that such a high Frobenius error is concerning, since it is largely driven by the number of genes and cells. That seems pretty typical to me.

I think 10 would definitely be a good value to investigate since it gives the most stable solution but it is also a good idea to look at some of the values greater than 10 such as 11 and 12 since the most stable solution isn't necessarily the most biologically accurate.

**Comment by avishai987** [comment]
I was wondering the same thing- I have a Frobenius error of about 10K-100K, Is that tell me that something is wrong?
![ACC19_cNMF k_selection](https://user-images.githubusercontent.com/79481420/169269576-8ee14268-57e8-4eab-8039-e421e3bc39ff.png)
